export const GLOSSARY_ENTRIES = [
  {
    term: "Change Data Capture",
    definition: "Techniques for detecting database mutations and streaming them downstream.",
  },
  {
    term: "Polling",
    definition: "Periodic queries against source tables to detect differences since the last scan.",
  },
  {
    term: "Transaction log",
    definition: "Append-only log of committed mutations; reliable source for log-based CDC.",
  },
  {
    term: "Snapshot",
    definition: "Initial bulk export of table rows taken before switching into incremental streaming.",
  },
  {
    term: "Backlog",
    definition: "Events buffered on the transport waiting for consumers to apply them.",
  },
  {
    term: "Lag",
    definition: "Elapsed time between an event committing at the source and being applied downstream.",
  },
  {
    term: "Offset",
    definition: "Monotonic pointer for the event bus that lets consumers resume without reprocessing.",
  },
  {
    term: "Tombstone",
    definition: "Delete marker emitted so downstream systems can purge rows even when no payload remains.",
  },
  {
    term: "Write amplification",
    definition: "Additional writes generated by a capture method compared to the originating workload.",
  },
];
