export default [
  {
    key: "intro",
    related: ["event-envelope", "snapshotting", "use-cases"],
    title: "Interactive Introduction to CDC",
    description:
      "An interactive dashboard covering core concepts, methods, architectures, and the tooling ecosystem.",
    href: "intro/",
    ctaLabel: "Dive In!",
    isRecommended: true,
    badge: { label: "Start Here", variant: "recommended" },
    tags: [{ label: "Core Concept", variant: "tag-concept" }],
    skillLevel: "Beginner",
  },
  {
    key: "event-envelope",
    related: ["intro", "exactly-once", "materialization", "schema-evolution"],
    title: "Event Envelope & Delivery Guarantees",
    description:
      "Keys vs payload, before/after images, tombstones; ALO vs EOS scope and per-key ordering.",
    href: "event-envelope/",
    tags: [{ label: "Core Concept", variant: "tag-concept" }],
    skillLevel: "Beginner",
  },
  {
    key: "materialization",
    related: ["which-row-wins", "deletes-stay-deleted", "event-envelope"],
    title: "Materialization 101 (Upsert/Delete)",
    description:
      "Practical MERGE patterns for upserts & deletes; compaction vs history tables; late-arrivals 101.",
    href: "materialization/",
    tags: [{ label: "Core Concept", variant: "tag-concept" }],
    skillLevel: "Intermediate",
  },
  {
    key: "snapshotting",
    related: ["backfill-resnapshot", "postgres-replication-slots", "intro"],
    title: "Snapshotting: The First Sync",
    description:
      "Learn how CDC pipelines perform the initial, consistent snapshot of a database before streaming live changes.",
    href: "snapshotting/",
    tags: [{ label: "Core Concept", variant: "tag-concept" }],
    skillLevel: "Intermediate",
  },
  {
    key: "exactly-once",
    related: ["is-cdc-exactly-once", "transactional-outbox", "which-row-wins"],
    title: "Exactly-Once Semantics",
    description: "Visual walkthrough of ALO vs EOS + transactional outbox.",
    href: "exactly-once/",
    tags: [{ label: "Advanced Pattern", variant: "tag-pattern" }],
    skillLevel: "Advanced",
  },
  {
    key: "is-cdc-exactly-once",
    related: ["exactly-once", "ops-offsets", "test-your-pipeline", "errata"],
    title: "Is CDC Exactly-Once? Per Hop",
    description:
      "Check any exactly-once claim hop by hop: Kafka Connect and Debezium opt-in settings, Kafka transactions, offsets in the sink, and how to verify.",
    href: "is-cdc-exactly-once/",
    ctaLabel: "Check the Claim",
    tags: [{ label: "Advanced Pattern", variant: "tag-pattern" }],
    skillLevel: "Advanced",
  },
  {
    key: "non-kafka-cdc",
    related: ["tooling", "ops-offsets", "connector-builder"],
    title: "CDC Without Kafka",
    description:
      "Debezium Server, the embedded engine, managed services and search-index sync: what each guarantees, what a crash repeats, and why the log position is the version.",
    href: "non-kafka-cdc/",
    ctaLabel: "Leave Kafka Out",
    tags: [{ label: "Advanced Pattern", variant: "tag-pattern" }],
    skillLevel: "Advanced",
  },
  {
    key: "transactional-outbox",
    related: ["exactly-once", "non-kafka-cdc", "cdc-data-contracts"],
    title: "Transactional Outbox and Relay",
    description:
      "The outbox pattern with Debezium's Outbox Event Router: why dual writes fail, what at-least-once means for the relay, and how consumers dedupe and order.",
    href: "transactional-outbox/",
    ctaLabel: "Publish It Right",
    tags: [{ label: "Advanced Pattern", variant: "tag-pattern" }],
    skillLevel: "Advanced",
  },
  {
    key: "multi-tenancy",
    related: ["partitioning", "security", "schema-evolution"],
    title: "Multi-Tenancy",
    description: "Isolation patterns, topic math, and rough egress estimates.",
    href: "multi-tenancy/",
    tags: [{ label: "Advanced Pattern", variant: "tag-pattern" }],
    skillLevel: "Advanced",
  },
  {
    key: "partitioning",
    related: ["which-row-wins", "multi-tenancy", "ops-offsets"],
    title: "Partitioning",
    description: "Partition keys, skew, late-arrivals, and audit loops.",
    href: "partitioning/",
    tags: [{ label: "Advanced Pattern", variant: "tag-pattern" }],
    skillLevel: "Advanced",
  },
  {
    key: "which-row-wins",
    related: ["materialization", "deletes-stay-deleted", "partitioning"],
    title: "Which Row Wins in Your Target",
    description:
      "Ordering and delete markers in BigQuery, Databricks, Hudi, Iceberg, Delta and Snowflake: what decides the winner and what to set.",
    href: "which-row-wins/",
    tags: [{ label: "Advanced Pattern", variant: "tag-pattern" }],
    skillLevel: "Advanced",
  },
  {
    key: "schema-evolution",
    related: ["cdc-data-contracts", "event-envelope", "backfill-resnapshot"],
    title: "Schema Evolution",
    description:
      "Handle schema changes gracefully with forward/backward compatibility and schema registries.",
    href: "schema-evolution/",
    tags: [{ label: "Advanced Pattern", variant: "tag-pattern" }],
    skillLevel: "Advanced",
  },
  {
    key: "cdc-data-contracts",
    related: ["schema-evolution", "event-envelope", "transactional-outbox"],
    title: "Data Contracts for Database Events",
    description:
      "What a consumer may rely on when the producer is a database: the envelope, which DDL breaks it, registry modes, and a gate that catches it.",
    href: "cdc-data-contracts/",
    ctaLabel: "Read the Contract",
    tags: [{ label: "Advanced Pattern", variant: "tag-pattern" }],
    skillLevel: "Advanced",
  },
  {
    key: "ops-offsets",
    related: ["reconciliation-surgery", "observability", "is-cdc-exactly-once"],
    title: "Ops: Offsets & Replays",
    description:
      "Offset stores, safe rewind, idempotency, and resync drills when things go sideways.",
    href: "ops-offsets/",
    tags: [{ label: "Ops", variant: "tag-ops" }],
    skillLevel: "Intermediate",
  },
  {
    key: "observability",
    related: ["ops-offsets", "postgres-replication-slots", "failure-drills"],
    title: "Observability Basics",
    description:
      "Golden signals (lag, throughput, error rate), alerting, and minimal dashboards to keep.",
    href: "observability/",
    tags: [{ label: "Ops", variant: "tag-ops" }],
    skillLevel: "Intermediate",
  },
  {
    key: "postgres-replication-slots",
    related: ["snapshotting", "observability", "sql-server-mysql-cdc"],
    title: "Postgres Replication Slots & WAL Growth",
    description:
      "A runbook for a Postgres disk filling behind a CDC slot: the checks, max_slot_wal_keep_size, Debezium heartbeats, and safe recovery.",
    href: "postgres-replication-slots/",
    tags: [{ label: "Ops", variant: "tag-ops" }],
    skillLevel: "Intermediate",
  },
  {
    key: "sql-server-mysql-cdc",
    related: ["postgres-replication-slots", "backfill-resnapshot", "tooling"],
    title: "SQL Server & MySQL CDC Specifics",
    description:
      "Positions, retention and what breaks for Debezium on MySQL and SQL Server: binlog purge, GTIDs, CDC cleanup jobs, LSNs, triage queries and runbooks.",
    href: "sql-server-mysql-cdc/",
    tags: [{ label: "Ops", variant: "tag-ops" }],
    skillLevel: "Intermediate",
  },
  {
    key: "backfill-resnapshot",
    related: ["snapshotting", "reconciliation-surgery", "deletes-stay-deleted"],
    title: "Backfill and Re-Snapshot Safely",
    description:
      "Reload history into a sink without overwriting newer changes: snapshot modes, incremental snapshots, Kafka replay, the position guard and a runbook.",
    href: "backfill-resnapshot/",
    tags: [{ label: "Ops", variant: "tag-ops" }],
    skillLevel: "Advanced",
  },
  {
    key: "non-relational",
    related: ["intro", "tooling", "event-envelope"],
    title: "CDC Beyond Relational Databases",
    description:
      "MongoDB change streams, DynamoDB Streams, and Cassandra CDC — and where each one breaks the WAL/binlog mental model.",
    href: "non-relational/",
    tags: [
      { label: "Core Concept", variant: "tag-concept" },
      { label: "Strategy", variant: "tag-strategy" },
    ],
    skillLevel: "Intermediate",
  },
  {
    key: "security",
    related: ["multi-tenancy", "cdc-data-contracts", "strategy"],
    title: "Security, PII & Access Control",
    description:
      "Mask columns before they reach the broker, size the privileges CDC actually needs, and plan for a log that outlives the row.",
    href: "security/",
    tags: [
      { label: "Ops", variant: "tag-ops" },
      { label: "Strategy", variant: "tag-strategy" },
    ],
    skillLevel: "Intermediate",
  },
  {
    key: "deletes-stay-deleted",
    related: ["which-row-wins", "backfill-resnapshot", "materialization"],
    title: "Deletes That Stay Deleted",
    description:
      "Delete events, Kafka tombstones and sink delete markers; why a late update can resurrect a row; and where a deleted row can still live (compaction, time travel, snapshots, backups).",
    href: "deletes-stay-deleted/",
    tags: [
      { label: "Advanced Pattern", variant: "tag-pattern" },
      { label: "Ops", variant: "tag-ops" },
    ],
    skillLevel: "Advanced",
  },
  {
    key: "reconciliation-surgery",
    related: ["ops-offsets", "backfill-resnapshot", "test-your-pipeline"],
    title: "Reconciliation & Offset Surgery",
    description:
      "Repair out-of-sync sinks and safely reset offsets. SQL diff patterns, checksum verification, and Kafka Connect REST API offset operations.",
    href: "reconciliation-surgery/",
    tags: [
      { label: "Advanced Pattern", variant: "tag-pattern" },
      { label: "Ops", variant: "tag-ops" },
    ],
    skillLevel: "Advanced",
  },
  {
    key: "use-cases",
    related: ["intro", "strategy", "case-study", "non-relational"],
    title: "Real-World Use Cases",
    description:
      "Explore practical applications of CDC, from real-time analytics to cache invalidation.",
    href: "use-cases/",
    tags: [{ label: "Core Concept", variant: "tag-concept" }],
    skillLevel: "Beginner",
  },
  {
    key: "strategy",
    related: ["use-cases", "case-study", "tooling"],
    title: "The Strategic Value of CDC",
    description:
      "Understand the business case and philosophical shift behind adopting an event-driven data culture.",
    href: "strategy/",
    tags: [{ label: "Strategy", variant: "tag-strategy" }],
    skillLevel: "Beginner",
  },
  {
    key: "tooling",
    related: ["quickstarts", "non-kafka-cdc", "connector-builder"],
    title: "The CDC Ecosystem",
    description:
      "A curated overview of the most popular open-source and commercial tools in the landscape (Debezium, Fivetran, etc).",
    href: "tooling/",
    tags: [{ label: "Tooling", variant: "tag-tooling" }],
    skillLevel: "Beginner",
  },
  {
    key: "case-study",
    related: ["use-cases", "strategy", "lab-kafka-debezium"],
    title: "Real-World Case Study",
    description:
      "Follow a mid-sized e-commerce company's journey from batch ETL to real-time CDC, including architecture decisions, implementation challenges, and business outcomes.",
    href: "case-study/",
    ctaLabel: "Read the Case Study",
    isRecommended: true,
    badge: { label: "Featured", variant: "recommended" },
    tags: [{ label: "Strategy", variant: "tag-strategy" }],
    skillLevel: "Intermediate",
  },
  {
    key: "lab-kafka-debezium",
    related: ["quickstarts", "cloud-labs", "tests"],
    title: "Hands-On Lab: Kafka + Debezium + Sinks",
    description:
      "Stand up Kafka, Connect, Postgres source & sink with guided copy-paste commands. Includes upsert patterns and schema evolution.",
    href: "lab-kafka-debezium/",
    ctaLabel: "Start the Lab",
    tags: [{ label: "Lab", variant: "tag-labs" }],
    skillLevel: "Intermediate",
  },
  {
    key: "quickstarts",
    related: ["lab-kafka-debezium", "cloud-labs", "tooling"],
    title: "Quickstarts",
    description:
      "Pick your source database and follow a 10–20 minute setup with checks and commands.",
    href: "quickstarts/",
    ctaLabel: "View Quickstarts",
    tags: [{ label: "Lab", variant: "tag-labs" }],
    skillLevel: "Beginner",
  },
  {
    key: "tests",
    related: ["test-your-pipeline", "failure-drills", "lab-kafka-debezium"],
    title: "Acceptance Tests",
    description:
      "Run shell scripts that confirm your lab stack is up, the connector is healthy, and events keep flowing after restarts.",
    href: "tests/",
    ctaLabel: "Verify Your Stack",
    tags: [{ label: "Lab", variant: "tag-labs" }],
    skillLevel: "Intermediate",
  },
  {
    key: "test-your-pipeline",
    related: ["tests", "failure-drills", "reconciliation-surgery"],
    title: "Testing a CDC Pipeline",
    description:
      "Contract, duplicate, out-of-order and replay tests for your own pipeline, with runnable examples and what not to test for.",
    href: "test-your-pipeline/",
    ctaLabel: "Write the Tests",
    tags: [
      { label: "Ops", variant: "tag-ops" },
      { label: "Advanced Pattern", variant: "tag-pattern" },
    ],
    skillLevel: "Intermediate",
  },
  {
    key: "failure-drills",
    related: ["test-your-pipeline", "observability", "dlq-triage"],
    title: "Failure Scenario Drills",
    description:
      "Hands-on drills to build troubleshooting fluency: backpressure, DLQ handling, schema drift, and offset replays.",
    href: "troubleshooting/failure-drills/",
    ctaLabel: "Start Drills",
    tags: [{ label: "Lab", variant: "tag-labs" }],
    skillLevel: "Advanced",
  },
  {
    key: "cloud-labs",
    related: ["quickstarts", "lab-kafka-debezium", "tooling"],
    title: "Cloud CDC Labs",
    description:
      "End-to-end CDC implementations with cloud-native platforms: AWS DMS, Snowflake, and Matillion.",
    href: "cloud-labs/",
    ctaLabel: "Explore Cloud Labs",
    tags: [{ label: "Lab", variant: "tag-labs" }],
    skillLevel: "Intermediate",
  },
  {
    key: "connector-builder",
    related: ["tooling", "debezium-decoder", "quickstarts"],
    title: "Connector Config Builder",
    description:
      "Generate Debezium configs for Postgres, MySQL, or Oracle in minutes.",
    href: "connector-builder/",
    ctaLabel: "Launch the Builder",
    tags: [{ label: "Tooling", variant: "tag-tooling" }],
    skillLevel: "Intermediate",
  },
  {
    key: "dlq-triage",
    related: ["failure-drills", "debezium-decoder", "observability"],
    title: "DLQ Triage Assistant",
    description:
      "Guided commands and playbooks for decoding and re-driving Kafka DLQ events.",
    href: "dlq-triage/",
    ctaLabel: "Try the Assistant",
    tags: [{ label: "Extras", variant: "tag-extras" }],
    skillLevel: "Advanced",
  },
  {
    key: "debezium-decoder",
    related: ["event-envelope", "connector-builder", "dlq-triage"],
    title: "Debezium Event Decoder",
    description:
      "Paste Kafka events to get before/after diffs and MERGE-ready SQL templates.",
    href: "debezium-decoder/",
    ctaLabel: "Decode an Event",
    tags: [{ label: "Extras", variant: "tag-extras" }],
    skillLevel: "Intermediate",
  },
  {
    key: "errata",
    related: ["exactly-once", "is-cdc-exactly-once", "event-envelope"],
    title: "Nuances & Errata",
    description:
      "Corrections, caveats, and sharp edges across CDC: effectively-once vs exactly-once, snapshots & replays, tombstones/compaction, schema evolution, and ops guardrails.",
    href: "errata/",
    ctaLabel: "See nuances",
    tags: [{ label: "Extras", variant: "tag-extras" }],
    skillLevel: "Advanced",
  },
];
