name: Sync README Status

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 4 * * 1' # weekly Monday 04:00 UTC

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Update README status
        run: node ai/scripts/sync-readme.mjs
      - name: Commit README
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: sync AI status section" || echo "No changes to commit"
          git push
