name: Deprecated Jekyll deploy (disabled)

description: Prevents the default Jekyll workflow from running on pushes so Eleventy can publish the site correctly.

on:
  workflow_dispatch:
    inputs:
      reason:
        description: Why are you running this deprecated workflow?
        required: false

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Abort with guidance
        run: |
          echo "This workflow intentionally does nothing." >&2
          echo "Use .github/workflows/deploy.yml to publish the Eleventy build." >&2
          exit 1
